os: linux
language: go
go:
  - 1.13.x
  - 1.14.x
  - tip
env:
  - GO111MODULE=on
matrix:
  allow_failures:
    - go: tip
script:
  - go test

deploy:
  - provider: script
    cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux